Create a Readme for Pikachus
DeanIsseyegh/smash-pen pull request #2
Opened 2019-04-24 11:54 UTC by JamesKerryBarnard

Pikachu (the best character) will not be able to read the main README, so i propose creating a Pikchu specific Readme.

2019-05-01 12:32 UTC, chuckydev commented
No.

2020-06-30 15:21 UTC, JamesKerryBarnard commented
Please Review this

2020-06-30 15:22 UTC, DeanIsseyegh commented
Pikachus ftilt comes out on frame 6, and his dthrow comboes into nair loops up to around 40% where it can be finished off with a dsmash.

You haven't included ANY of this info in your PR.

2020-06-30 15:22 UTC, chuckydev requested changes

2020-06-30 15:22 UTC, chuckydev commented on PIKAREADME.MD
> +CHUUUUUUUUUU
Needs a picture of Pikachu

2020-07-09 10:02 UTC, JamesKerryBarnard commented on PIKAREADME.MD
> +CHUUUUUUUUUU
Agreed. +1 a pika pic

2022-02-04 16:46 UTC, JamesKerryBarnard commented
Hello @DeanIsseyegh I have added a pikachu pic

2022-02-23 14:16 UTC, closed without merging